dependencies:
- name: postgresql
  version: 6.2.1
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 9.0.2
  repository: https://kubernetes-charts.storage.googleapis.com/
