version: 0.7.6

# Replace this with your own secret_key (used to sign cookies and others)
secret_key: "y(qs_&z!7u+!7rq6z3fx=p)pfx_ah3l(i&#p(dx5cu=d3=knq3"

config:
  # Enable error reporting (errors are sent to sentry.beryju.org)
  error_reporting: true

  # Only allow single sign-on, configured below
  external_auth_only: false

  # OIDC Configuration
  # Callback URL: <base url>/_/oidc/callback/
  oidc:
    enabled: false
    client_id: ""
    client_secret: ""
    auth_url: ""
    token_url: ""
    user_url: ""

deployment:
  webInstances: 2
  workerInstances: 1
  # To disable tier0, set the values below to 0
  tier0Instances: 2
  grpcInstances: 1

postgresql:
  postgresqlUsername: p2
  postgresqlDatabase: p2

ingress:
  enabled: true
  serve:
    hosts:
      - "i.p2.local"
  hosts:
    - "p2.local"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - i.p2.local
  #      - p2.local
