# Global Variables
before_script:
  - "python3 -m pip install -U virtualenv"
  - "virtualenv env"
  - "source env/bin/activate"
  - "pip3 install -U -r requirements.txt -r requirements-dev.txt"
stages:
  - test
  - build
  - docs
image: python:3.5

isort:
  script:
    - isort -c -sg env
  stage: test
migrations:
  script:
    - python manage.py migrate
  stage: test
prospector:
  script:
    - prospector
  stage: test
pylint:
  script:
    - pylint pyazo
  stage: test
coverage:
  script:
    - coverage run manage.py test
    - coverage report
  stage: test

package-docker:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKER_USERNAME\",\"password\":\"$DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination beryjuorg/pyazo:stable --destination beryjuorg/pyazo:1.8.8
  stage: build
  only:
    - tags
    - docker-ci-test
    - /^debian/.*$/
package-3.5:
  before_script:
    - apt update
    - apt install -y build-essential debhelper devscripts equivs python3 python3-pip
    - cp debian/control-3.5 debian/control
    - mk-build-deps debian/control
    - apt install ./*build-deps*deb -f -y
    - "python3 -m pip install -U virtualenv"
    - "virtualenv env"
    - "source env/bin/activate"
    - "pip3 install -U -r requirements.txt -r requirements-dev.txt"
  image: debian
  script:
    - debuild -us -uc
    - cp ../pyazo*.deb .
    - python manage.py nexus_upload
  artifacts:
    paths:
    - pyazo-python3.5*deb
    expire_in: 2 days
  stage: build
  only:
  - tags
  - /^debian/.*$/
package-3.6:
  before_script:
    - apt update
    - apt install -y build-essential debhelper devscripts equivs python3 python3-pip
    - cp debian/control-3.6 debian/control
    - mk-build-deps debian/control
    - apt install ./*build-deps*deb -f -y
    - "python3 -m pip install -U virtualenv"
    - "virtualenv env"
    - "source env/bin/activate"
    - "pip3 install -U -r requirements.txt -r requirements-dev.txt"
  image: debian:buster
  script:
    - debuild -us -uc
    - cp ../pyazo*.deb .
    - python manage.py nexus_upload
  artifacts:
    paths:
    - pyazo-python3.6*deb
    expire_in: 2 days
  stage: build
  only:
    - tags
    - /^debian/.*$r

docs:
  stage: docs
  only:
  - master
  - tags
  - /^debian/.*$/
  environment:
    name: docs
    url: "https://pyazo.beryju.org/docs/"
  script:
    - apt update
    - apt install -y rsync
    - "mkdir ~/.ssh"
    - "cp .gitlab/known_hosts ~/.ssh/"
    - "pip3 install -U -r requirements-docs.txt"
    - "eval $(ssh-agent -s)"
    - "echo \"${CI_SSH_PRIVATE}\" | ssh-add -"
    - mkdocs build
    - 'rsync -avh --delete site/* "beryjuorg@ory1-web-prod-1.ory1.beryju.org:pyazo.beryju.org/docs/"'

web:
  stage: docs
  only:
  - master
  - tags
  - /^debian/.*$/
  environment:
    name: docs
    url: "https://pyazo.beryju.org/"
  script:
    - apt update
    - apt install -y rsync
    - "mkdir ~/.ssh"
    - "cp .gitlab/known_hosts ~/.ssh/"
    - "eval $(ssh-agent -s)"
    - "echo \"${CI_SSH_PRIVATE}\" | ssh-add -"
    - 'rsync -avh --delete web/* "beryjuorg@ory1-web-prod-1.ory1.beryju.org:pyazo.beryju.org/"'
