# Global Variables
stages:
  - build-base-image
  - build-dev-image
  - test
  - build
image: docker.beryju.org/p2/dev:latest

variables:
  POSTGRES_DB: p2
  POSTGRES_USER: p2
  POSTGRES_PASSWORD: "EK-5jnKfjrGRm<77"
  P2_POSTGRESQL__USER: p2
  P2_POSTGRESQL__PASSWORD: "EK-5jnKfjrGRm<77"

before_script:
  # Ensure all dependencies are installed, even those not included in p2/base
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

create-base-image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.base --destination docker.beryju.org/p2/base:latest --destination docker.beryju.org/p2/base:0.8.0-rc1
  stage: build-base-image
  only:
    refs:
      - tags
      - /^version/.*$/

build-dev-image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.dev --destination docker.beryju.org/p2/dev:latest --destination docker.beryju.org/p2/dev:0.8.0-rc1
  stage: build-dev-image
  only:
    refs:
      - tags
      - /^version/.*$/

isort:
  script:
    - isort -c -sg env
  stage: test
  services:
  - postgres:latest
  - redis:latest
migrations:
  script:
    - python manage.py migrate
  stage: test
  services:
  - postgres:latest
  - redis:latest
prospector:
  script:
    - prospector
  stage: test
  services:
  - postgres:latest
  - redis:latest
pylint:
  script:
    - pylint p2
  stage: test
  services:
  - postgres:latest
  - redis:latest
coverage:
  script:
    - env
    - coverage run manage.py test
    - coverage report
    - coverage html
  stage: test
  services:
  - postgres:latest
  - redis:latest
tier0:
  variables:
    GO111MODULE: 'on'
    GOOS: linux
    GOARCH: amd64
    CGO_ENABLED: 0
  before_script: []
  script:
    - mkdir -p /go/src/git.beryju.org/BeryJu.org/
    - cd /go/src/git.beryju.org/BeryJu.org/
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME/tier0
    - go mod download
    - go build -ldflags "-s -w" -v -o /go/bin/tier0
  image: golang:latest
  stage: test

build-p2-server:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination docker.beryju.org/p2/server:latest --destination docker.beryju.org/p2/server:0.8.0-rc1
  only:
    - tags
    - /^version/.*$/
build-static:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.static --destination docker.beryju.org/p2/static:latest --destination docker.beryju.org/p2/static:0.8.0-rc1
  only:
    - tags
    - /^version/.*$/
  # running collectstatic fully initialises django, hence we need that databases
  services:
    - postgres:latest
    - redis:latest
build-tier0:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR/tier0 --dockerfile $CI_PROJECT_DIR/tier0/Dockerfile --destination docker.beryju.org/p2/tier0:latest --destination docker.beryju.org/p2/tier0:0.8.0-rc1
  only:
    - tags
    - /^version/.*$/
build-operator:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR/operator --dockerfile $CI_PROJECT_DIR/operator/build/Dockerfile --destination docker.beryju.org/p2/operator:latest --destination docker.beryju.org/p2/operator:0.8.0-rc1
  only:
    - tags
    - /^version/.*$/
build-docs:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/docs/Dockerfile --destination docker.beryju.org/p2/docs:latest --destination docker.beryju.org/p2/docs:0.8.0-rc1
  only:
    - tags
    - /^version/.*$/
