# Global Variables
stages:
  - build-build-image
  - test
  - build
  - package
image: docker.beryju.org/p2/build-base:latest
services:
  - postgres:latest
  - redis:latest

variables:
  POSTGRES_DB: p2
  POSTGRES_USER: p2
  POSTGRES_PASSWORD: "EK-5jnKfjrGRm<77"


before_script:
  # Ensure all dependencies are installed, even those not included in p2/build-base
  - pip install -r requirements-dev.txt

create-build-image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.build-base --destination docker.beryju.org/p2/build-base:latest --destination docker.beryju.org/p2/build-base:0.6.2
  stage: build-build-image
  only:
    refs:
      - tags
      - /^version/.*$/

isort:
  script:
    - isort -c -sg env
  stage: test
migrations:
  script:
    - python manage.py migrate
  stage: test
prospector:
  script:
    - prospector
  stage: test
pylint:
  script:
    - pylint p2
  stage: test
coverage:
  script:
    - coverage run manage.py test
    - coverage report
    - coverage html
  stage: test

build-p2-server:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination docker.beryju.org/p2/server:latest --destination docker.beryju.org/p2/server:0.6.2
  only:
    - tags
    - /^version/.*$/
build-p2-tier0:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR/tier0 --dockerfile $CI_PROJECT_DIR/tier0/Dockerfile --destination docker.beryju.org/p2/tier0:latest --destination docker.beryju.org/p2/tier0:0.6.2
  only:
    - tags
    - /^version/.*$/

package-helm:
  stage: package
  script:
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
    - helm init --client-only
    - helm dependency build install/helm/p2
    - helm package install/helm/p2
  artifacts:
    paths:
      - p2-*.tgz
    expire_in: 1 week
  only:
    - tags
    - /^version/.*$/
package-installer:
  stage: package
  script:
    - echo Hello World
  artifacts:
    paths:
      - install/install.sh
    expire_in: 1 week
  only:
    - tags
    - /^version/.*$/

# Manual tasks
# build-protos:
#   stage: manual
#   script:
#     - python -m grpc_tools.protoc -I=. --python_out=p2/grpc/ --grpc_python_out=p2/grpc/ protos/*
#     - protoc -I=. protos/*.proto --go_out=plugins=grpc:tier0/internal/
#     # - sed -i -E 's/^\(import.*_pb2\)/from . \1/' p2/grpc/protos/*.py
#   only:
#     - never
