# Global Variables
before_script:
  - "python3 -m pip install -U virtualenv"
  - "virtualenv env"
  - "source env/bin/activate"
  - "pip3 install -U -r requirements.txt -r requirements-dev.txt"
stages:
  - test
  - build
image: python:3.5

isort:
  script:
    - "isort -c -sg env"
  stage: test
  cache:
    paths:
      - env/
migrations:
  script:
    - "python manage.py migrate"
  stage: test
  cache:
    paths:
      - env/
prospector:
  script:
    - "prospector"
  stage: test
  cache:
    paths:
      - env/
pylint:
  script:
    - "pylint pyazo"
  stage: test
  cache:
    paths:
      - env/

package:
  before_script:
    - apt update && apt install -y python3 libssl-dev libffi-dev python-dev dh-systemd dh-exec wget dh-virtualenv debhelper git-buildpackage python3-pip dirmngr gpgv2
  image: debian
  script:
    - python3 -m pip install -U virtualenv
    - debuild -us -uc
    - export GPG_TTY=$(tty)
    - mkdir -p ~/.gnupg/private-keys-v1.d
    - chmod 700 ~/.gnupg/private-keys-v1.d
    - echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
    - gpg-agent --daemon &
    - echo "${CI_GPG_PRIVATE}" | gpg --import --batch
    - echo "${CI_GPG_KEY}" | gpg --batch --pinentry-mode loopback --yes --passphrase-fd 0 -a --output pyazo_singed.deb --detach-sig ../pyazo_*.deb
  stage: build
  artifacts:
    paths:
    - pyazo_singed.deb
    expire_in: 2 days
  # only:
  #   - tags
  cache:
    paths:
      - env/
