# Global Variables
stages:
  - build-build-image
  - test
  - build
  - docs
image: docker.beryju.org/p2/build-base:latest
services:
  - postgres:latest
  - redis:latest

variables:
  POSTGRES_DB: p2
  POSTGRES_USER: p2
  POSTGRES_PASSWORD: "EK-5jnKfjrGRm<77"


create-build-image:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.build-base --destination docker.beryju.org/p2/build-base:latest --destination docker.beryju.org/p2/build-base:0.5.1
  stage: build-build-image
  only:
    refs:
      - tags
      - /^version/.*$/

isort:
  script:
    - isort -c -sg env
  stage: test
migrations:
  script:
    - python manage.py migrate
  stage: test
prospector:
  script:
    - prospector
  stage: test
pylint:
  script:
    - pylint p2
  stage: test
coverage:
  script:
    - coverage run manage.py test
    - coverage report
    - coverage html
  stage: test

package-docker:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"docker.beryju.org\":{\"auth\":\"$DOCKER_AUTH\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination docker.beryju.org/p2/server:latest --destination docker.beryju.org/p2/server:0.5.1
  stage: build
  only:
    - tags
    - /^version/.*$/
package-helm:
  stage: build
  script:
    - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get | bash
    - helm init --client-only
    - helm dependency build install/helm/p2
    - helm package install/helm/p2
  artifacts:
    paths:
      - p2-*.tgz
    expire_in: 1 week
  only:
    - tags
    - /^version/.*$/
package-installer:
  stage: build
  script:
    - echo Hello World
  artifacts:
    paths:
      - install/install.sh
    expire_in: 1 week
  only:
    - tags
    - /^version/.*$/
