# Global Variables
before_script:
  - "python3 -m pip install -U virtualenv"
  - "virtualenv env"
  - "source env/bin/activate"
  - "pip3 install -U -r requirements.txt -r requirements-dev.txt"
stages:
  - test
  - build
image: python:3.6

isort:
  script:
    - "isort -c -vb -sg env -b importlib"
  stage: test
  cache:
    paths:
      - env/
migrations:
  script:
    - "python manage.py migrate"
  stage: test
  cache:
    paths:
      - env/
prospector:
  script:
    - "prospector"
  stage: test
  cache:
    paths:
      - env/
pylint:
  script:
    - "pylint --load-plugins pylint_django pyazo"
  stage: test
  cache:
    paths:
      - env/

package:
  before_script:
    - apt update && apt install -y python3
  image: debian
  script:
    - apt install -y dh-systemd dh-exec wget dh-virtualenv debhelper git-buildpackage
    - debuild -us -uc
    - echo "${CI_GPG_PRIVATE}" | gpg --import
    - echo "${CI_GPG_KEY}" | gpg --batch --yes --passphrase-fd 0 -a --output pyazo_singed.deb --detach-sig ../build-area/pyazo_*.deb
  stage: build
  artifacts:
    paths:
    - pyazo_singed.deb
    expire_in: 2 days
  cache:
    paths:
      - env/
