# Global Variables
before_script:
  - "python3 -m pip install -U virtualenv"
  - "virtualenv env"
  - "source env/bin/activate"
  - "pip3 install -U -r requirements.txt -r requirements-dev.txt"
stages:
  - test
  - build
image: python:3.5

isort:
  script:
    - "isort -c -sg env"
  stage: test
migrations:
  script:
    - "python manage.py migrate"
  stage: test
prospector:
  script:
    - "prospector"
  stage: test
pylint:
  script:
    - "pylint pyazo"
  stage: test

package-3.5:
  before_script:
    - apt update && apt install -y build-essential debhelper devscripts equivs
    - mk-build-deps --install debian/control
  image: debian
  script:
    - python3 -m pip install -U virtualenv
    - debuild -us -uc
    - mv ../pyazo*.deb .
  stage: build
  artifacts:
    paths:
    - pyazo-python3.5*deb
    expire_in: 2 days
package-3.6:
  before_script:
    - apt update && apt install -y build-essential debhelper devscripts equivs
    - mk-build-deps --install debian/control
  image: debian:buster
  script:
    - python3 -m pip install -U virtualenv
    - debuild -us -uc
    - mv ../pyazo*.deb .
  stage: build
  artifacts:
    paths:
    - pyazo-python3.6*deb
    expire_in: 2 days

