# Global Variables
before_script:
  - "python3 -m pip install -U virtualenv"
  - "virtualenv env"
  - "source env/bin/activate"
  - "pip3 install -U -r requirements.txt -r requirements-dev.txt"
stages:
  - test
  - build
image: python:3.5

isort:
  script:
    - "isort -c -sg env"
  stage: test
migrations:
  script:
    - "python manage.py migrate"
  stage: test
prospector:
  script:
    - "prospector"
  stage: test
pylint:
  script:
    - "pylint pyazo"
  stage: test

package-3.5:
  before_script:
    - apt update
    - apt install -y build-essential debhelper devscripts equivs python3 python3-pip
    - cp debian/control-3.5 debian/control
    - mk-build-deps debian/control
    - apt install ./*build-deps*deb -f -y
    - "python3 -m pip install -U virtualenv"
    - "virtualenv env"
    - "source env/bin/activate"
    - "pip3 install -U -r requirements.txt -r requirements-dev.txt"
  image: debian
  script:
    - debuild -us -uc
    - python manage.py nexus_upload
  stage: build
  only:
  - tags
  - /^debian/.*$/
package-3.6:
  before_script:
    - apt update
    - apt install -y build-essential debhelper devscripts equivs python3 python3-pip
    - cp debian/control-3.6 debian/control
    - mk-build-deps debian/control
    - apt install ./*build-deps*deb -f -y
    - "python3 -m pip install -U virtualenv"
    - "virtualenv env"
    - "source env/bin/activate"
    - "pip3 install -U -r requirements.txt -r requirements-dev.txt"
  image: debian:buster
  script:
    - debuild -us -uc
    - python manage.py nexus_upload
  stage: build
  only:
    - tags
    - /^debian/.*$/
