site_name: p2 Docs
nav:
  - Home: index.md
  - Installation:
      - Single-Node Installation: installation/single-node-install.md
      - Installation: installation/install.md
  - Components:
      - Image-attribute Scanning: components/image-attribute-scanning.md
      - Quota: components/quota.md
      - Public Access: components/public-access.md
      - Replication: components/replication.md
      - Expiry: components/expiry.md
  - Migration:
      - Migrating from pyazo: migrating-from-pyazo.md

repo_url: https://git.beryju.org/BeryJu.org/p2
theme:
  name: bootstrap4
