dependencies:
- name: redis
  version: 5.1.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: mariadb
  version: 5.2.3
  repository: https://kubernetes-charts.storage.googleapis.com/
