apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: p2s.k8s.beryju.org
spec:
  group: k8s.beryju.org
  names:
    kind: P2
    listKind: P2List
    plural: p2s
    singular: p2
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
