---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: p2-docs
  namespace: prod-p2-docs
  labels:
    app.kubernetes.io/name: p2-docs
    app.kubernetes.io/managed-by: p2-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: p2-docs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: p2-docs
    spec:
      containers:
        - name: p2-docs
          image: "docker.beryju.org/p2/docs:latest"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 10m
              memory: 20Mi
            requests:
              cpu: 10m
              memory: 20Mi
