apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-echo-service
  labels:
    k8s-app: demo-echo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: demo-echo-service
  template:
    metadata:
      labels:
        k8s-app: demo-echo-service
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: echo-service
        image: electroma/ingress-demo-echosvc-amd64:0.1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-echo-service
  labels:
    k8s-app: demo-echo-service
    k8s.p2.io/component: web
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    k8s-app: demo-echo-service
