apiVersion: v1
kind: Service
metadata:
  name: p2-t1-http
  labels:
    app.kubernetes.io/name: p2-t1
spec:
  type: ClusterIP
  ports:
    - port: 8092
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: p2-t1
