---
apiVersion: k8s.beryju.org/v1alpha1
kind: P2
metadata:
  name: example-p2
spec:
  version: 0.8.0rc1

  secret_key: "r-9k#x4tkk2e8%=(9hf#^v4&=5z2)^gzn^)l*_=z+&0a97kwd8"
  redis:
    password: "ThisIsNotASecurePassword!"
  postgresql:
    postgresqlPassword: "ThisIsNotASecurePassword!"

  config:
    # Enable error reporting (errors are sent to sentry.beryju.org)
    error_reporting: true

    # Only allow single sign-on, configured below
    external_auth_only: false

    # OIDC Configuration
    # Callback URL: <base url>/_/oidc/callback/
    oidc:
      enabled: false
      client_id: ""
      client_secret: ""
      auth_url: ""
      token_url: ""
      user_url: ""

  deployment:
    webInstances: 1
    workerInstances: 1
    # To disable tier0, set the values below to 0
    tier0Instances: 2
    grpcInstances: 1

  ingress:
    enabled: true
    serve:
      hosts:
        - "i.p2.local"
    hosts:
      - "p2.local"
    tls:
     - secretName: example-p2-tls
       hosts:
         - i.p2.local
         - p2.local

