apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: p2-operator
  template:
    metadata:
      labels:
        name: p2-operator
    spec:
      serviceAccountName: p2-operator
      containers:
        - name: p2-operator
          image: docker.beryju.org/p2/operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "p2-operator"
