apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "p2.fullname" . }}-config
data:
  config.yml: |
    databases:
      default:
        engine: django.db.backends.postgresql
        name: "{{ .Values.postgresql.postgresqlDatabase }}"
        user: "{{ .Values.postgresql.postgresqlUsername }}"
        password: "{{ .Values.postgresql.postgresqlPassword }}"
        host: "{{ .Release.Name }}-postgresql"
        port: ''

    cache: "redis://:{{ .Values.redis.password }}@{{ .Release.Name }}-redis-master/0"
    message_queue:
      broker: "redis://:{{ .Values.redis.password }}@{{ .Release.Name }}-redis-master/1"
      results: "redis://:{{ .Values.redis.password }}@{{ .Release.Name }}-redis-master/1"

    debug: false

    error_report_enabled: {{ .Values.config.error_reporting }}

    s3:
      base_domain: {{ (index .Values.ingress.hosts 0) | quote }}

    # Set this to true if you only want to use external authentication
    external_auth_only: {{ .Values.config.external_auth_only }}

    # Callback URL: <base url>/_/oidc/callback/
    # oidc:
    #   enabled: false
    #   client_id: ""
    #   client_secret: ""
    #   auth_url: ""
    #   token_url: ""
    #   user_url: ""
    oidc: {{ toYaml .Values.config.oidc | nindent 6 }}

    {{- if .Values.config.secret_key }}
    secret_key: {{ .Values.config.secret_key }}
    {{- else }}
    secret_key: {{ randAlphaNum 50 }}
    {{- end }}
