{{- if .Values.ingress.serve.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "p2.fullname" . }}-grpc
  labels:
    app.kubernetes.io/name: {{ include "p2.name" . }}
    helm.sh/chart: {{ include "p2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s.p2.io/component: grpc
spec:
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "p2.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    k8s.p2.io/component: grpc
{{- end }}
