apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "p2.fullname" . }}-grpc
  labels:
    app.kubernetes.io/name: {{ include "p2.name" . }}
    helm.sh/chart: {{ include "p2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    k8s.p2.io/deployment: grpc
spec:
  replicas: {{ .Values.deployment.grpcInstances }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "p2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "p2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        k8s.p2.io/component: grpc
      annotations:
        prometheus.io/scrape: "true"
        field.cattle.io/workloadMetrics: '[{"path":"/metrics","port":9102,"schema":"HTTP"}]'
    spec:
      securityContext:
        fsGroup: 100
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "p2.fullname" . }}-config
        - name: media-storage
          persistentVolumeClaim:
            claimName: {{ include "p2.fullname" . }}-pvc-app-storage
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.beryju.org/p2/server:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["./manage.py"]
          args: ["grpc"]
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: prometheus
              containerPort: 9102
              protocol: TCP
          env:
            - name: P2_REDIS_HOST
              value: "{{ .Release.Name }}-redis-master"
            - name: P2_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-redis"
                  key: redis-password
            - name: P2_PSQL_DBNAME
              value: "{{ .Values.postgresql.postgresqlDatabase }}"
            - name: P2_PSQL_USERNAME
              value: "{{ .Values.postgresql.postgresqlUsername }}"
            - name: P2_PSQL_HOST
              value: "{{ .Release.Name }}-postgresql"
            - name: P2_PSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Release.Name }}-postgresql"
                  key: postgresql-password
          volumeMounts:
            - mountPath: /etc/p2
              name: config-volume
            - mountPath: /storage
              name: media-storage
          resources:
            requests:
              cpu: 500m
              memory: 200M
            limits:
              cpu: 1000m
              memory: 250M
