apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "p2.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "p2.fullname" . }}-role
rules:
- apiGroups:
    - extensions
    - apps
  resources:
    - deployments
    - deployments/scale
  verbs:
    - get
    - list
    - patch
- apiGroups:
    - autoscaling
  resources:
    - horizontalpodautoscalers
  verbs:
    - create
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "p2.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "p2.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "p2.fullname" . }}
