apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "p2.fullname" . }}-static
  labels:
    app.kubernetes.io/name: {{ include "p2.name" . }}
    helm.sh/chart: {{ include "p2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "p2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "p2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        k8s.p2.io/component: static
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.beryju.org/p2/static:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /_/healthz
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
            httpGet:
              path: /_/healthz
              port: http
          resources:
            requests:
              cpu: 10m
              memory: 10M
            limits:
              cpu: 20m
              memory: 20M

