{{- if .Values.beta_enable_tier0 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "p2.fullname" . }}-tier0
  labels:
    app.kubernetes.io/name: {{ include "p2.name" . }}
    helm.sh/chart: {{ include "p2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8092
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "p2.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    k8s.p2.io/component: tier0
{{- end }}
