{{- if .Values.beta_enable_tier0 -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "p2.fullname" . }}-tier0
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "p2.fullname" . }}-tier0-role
rules:
- apiGroups: [""]
  resources:
  - services
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "p2.fullname" . }}-tier0
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "p2.fullname" . }}-tier0-role
subjects:
  - kind: ServiceAccount
    name: {{ include "p2.fullname" . }}-tier0
{{- end }}
