{{- if .Values.beta_enable_tier0 -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "p2.fullname" . }}-tier0
  labels:
    app.kubernetes.io/name: {{ include "p2.name" . }}
    helm.sh/chart: {{ include "p2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.deployment.tier0Instances }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "p2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "p2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        k8s.p2.io/component: tier0
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.beryju.org/p2/tier0:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8092
              protocol: TCP
            - name: http-cache
              containerPort: 8093
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 5
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 20
            timeoutSeconds: 5
            httpGet:
              path: /
              port: http
{{- end }}
