apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "p2.fullname" . }}-worker
  labels:
    app.kubernetes.io/name: {{ include "p2.name" . }}
    helm.sh/chart: {{ include "p2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "p2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "p2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        k8s.p2.io/component: worker
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "p2.fullname" . }}-config
        - name: media-storage
          persistentVolumeClaim:
            claimName: {{ include "p2.fullname" . }}-pvc-app-storage
      initContainers:
        - name: fix-volume-permissions
          image: busybox
          command: ["sh", "-c", "mkdir /storage/tmp && chown -R 100: /storage"]
          volumeMounts:
            - mountPath: /storage
              name: media-storage
      containers:
        - name: {{ .Chart.Name }}
          image: "docker.beryju.org/p2/server:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command: ["./manage.py", "worker"]
          volumeMounts:
            - mountPath: /etc/p2
              name: config-volume
            - mountPath: /storage
              name: media-storage
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
