apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: p2
  namespace: kube-system
spec:
  chart: https://pkg.beryju.org/repository/helm/p2-0.1.4.tgz
  targetNamespace: p2
  valuesContent: |-
    ingress:
      enabled: true
      hosts:
        - '%INGRESS_HOST%' # Replaced by install script
    # Since this is made for a single-node deployment, we disable most of the HA pods
    postgresql:
      postgresqlDatabase: p2
      postgresqlUsername: p2
      postgresqlPassword: 'kMxZy2cxr8xyK5SL'
      persistence:
        existingClaim: p2-pvc-postgresql
    redis:
      password: 'kMxZy2cxr8xyK5SL'
      master:
        persistence:
          # Since redis is only used as cache, persistence is not needed
          enabled: false
      cluster:
        enabled: false
    rabbitmq:
      rabbitmq:
        username: p2
        password: 'kMxZy2cxr8xyK5SL'
        clustering:
          k8s_domain: p2.baked
        extraConfiguration: |-
          cluster_formation.k8s.host = kubernetes.default.svc.p2.baked
      persistence:
        enabled: false
