apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: p2
  namespace: kube-system
spec:
  chart: https://pkg.beryju.org/repository/helm/p2-0.1.3.tgz
  targetNamespace: p2
  set:
    ingress:
      enabled: true
      hosts:
        # - '%INGRESS_HOST%' # Replaced by install script
        - 'p2.52.169.203.176.nip.io'
    # Since this is made for a single-node deployment, we disable most of the HA pods
    postgresql:
      postgresqlUsername: p2
      postgresqlDatabase: p2
      postgresqlPassword: 'todo: autogenerate this password somehow'
      persistence:
        existingClaim: p2-pvc-postgresql
    redis:
      password: 'todo: autogenerate this password somehow'
      master:
        persistence:
          # Since redis is only used as cache, persistence is not needed
          enabled: false
      cluster:
        enabled: false
    rabbitmq:
      rabbitmq:
        username: p2
        password: 'todo: autogenerate this password somehow'
      persistence:
        enabled: false
