---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: p2
  namespace: kube-system
spec:
  chart: https://docker.beryju.org/chartrepo/p2/charts/p2-0.7.5.tgz
  targetNamespace: p2
  valuesContent: |-
    deployment:
      webInstances: %WEB_INSTANCES%
      tier0Instances: %SERVE_INSTANCES%
      grpcInstances: 1
    ingress:
      enabled: true
      hosts:
        - "%HOST%"
      serve:
        hosts:
          - "%SERVE_HOST%"
    postgresql:
      postgresqlDatabase: p2
      postgresqlUsername: p2
      postgresqlPassword: '%PASSWORD%'
    redis:
      password: '%PASSWORD%'
      cluster:
        enabled: false
