---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: p2
  namespace: kube-system
spec:
  chart: https://docker.beryju.org/chartrepo/p2/charts/p2-0.7.4.tgz
  targetNamespace: p2
  valuesContent: |-
    deployment:
      webInstances: 1
      workerInstances: 1
      tier0Instances: 0
      grpcInstances: 0
    ingress:
      enabled: false
    postgresql:
      postgresqlDatabase: p2
      postgresqlUsername: p2
      postgresqlPassword: '%PASSWORD%'
    redis:
      password: '%PASSWORD%'
      cluster:
        enabled: false
