---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: p2
  namespace: kube-system
spec:
  chart: https://docker.beryju.org/chartrepo/p2/charts/p2-0.7.0-rc8.tgz
  targetNamespace: p2
  valuesContent: |-
    deployment:
      webInstances: %WEB_INSTANCES%
    ingress:
      enabled: true
      hosts:
        - "%HOST%"
      serve:
        enabled: %SERVE_ENABLED%
        hosts:
          - "%SERVE_HOST%"
    # Since this is made for a single-node deployment, we disable most of the HA pods
    postgresql:
      postgresqlDatabase: p2
      postgresqlUsername: p2
      postgresqlPassword: '%PASSWORD%'
    redis:
      password: '%PASSWORD%'
      cluster:
        enabled: false
