apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: p2
  namespace: kube-system
spec:
  chart: https://docker.beryju.org/chartrepo/p2/charts/p2-0.5.1.tgz
  targetNamespace: p2
  valuesContent: |-
    deployment:
      webInstances: %WEB_INSTANCES%
    ingress:
      enabled: true
      hosts:
        - '%INGRESS_HOST%' # Replaced by install script
        - '*.%INGRESS_HOST%' # Wildcard for S3
    # Since this is made for a single-node deployment, we disable most of the HA pods
    postgresql:
      postgresqlDatabase: p2
      postgresqlUsername: p2
      postgresqlPassword: '%PASSWORD%'
    redis:
      password: '%PASSWORD%'
      master:
        persistence:
          # Since redis is only used as cache, persistence is not needed
          enabled: false
      cluster:
        enabled: false
    rabbitmq:
      rabbitmq:
        username: p2
        password: '%PASSWORD%'
        clustering:
          k8s_domain: p2.baked
        extraConfiguration: |-
          cluster_formation.k8s.host = kubernetes.default.svc.p2.baked
      persistence:
        enabled: false
