apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "p2.fullname" . }}-config
data:
  config.yml: |
    debug: false

    error_report_enabled: {{ .Values.config.error_reporting }}

    s3:
      base_domain: {{ (index .Values.ingress.hosts 0) | quote }}

    # Set this to true if you only want to use external authentication
    external_auth_only: {{ .Values.config.external_auth_only }}

    # Callback URL: <base url>/_/oidc/callback/
    # oidc:
    #   enabled: false
    #   client_id: ""
    #   client_secret: ""
    #   auth_url: ""
    #   token_url: ""
    #   user_url: ""
    oidc: {{ toYaml .Values.config.oidc | nindent 6 }}

    secret_key: env://P2_SECRET_KEY
