apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "p2.fullname" . }}-config
data:
  debug: 'false'
  error_report_enabled: {{ .Values.config.error_reporting | quote }}
  s3.base_domain: {{ (index .Values.ingress.hosts 0) | quote }}
  # Set this to true if you only want to use external authentication
  external_auth_only: {{ .Values.config.external_auth_only | quote }}
  # Callback URL: <base url>/_/oidc/callback/
  {{- if .Values.config.oidc.enabled -}}
  oidc.enabled: 'true'
  oidc.client_id: '{{ .Values.config.oidc.client_id }}'
  oidc.client_secret: '{{ .Values.config.oidc.client_secret }}'
  oidc.auth_url: '{{ .Values.config.oidc.auth_url }}'
  oidc.token_url: '{{ .Values.config.oidc.token_url }}'
  oidc.user_url: '{{ .Values.config.oidc.user_url }}'
  {{ end }}
