---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "p2.fullname" . }}-pvc-app-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
