apiVersion: v1
kind: Secret
metadata:
  name: {{ template "p2.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "p2.name" . }}
    helm.sh/chart: {{ template "p2.chart" . }}
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
type: Opaque
data:
  secret_key: {{ randAlphaNum 50 | sha256sum | b64enc | quote }}
